name: csim
title: "Clint Simon"
author: "Clint Simon"
url: "http://clintsimon.com"
domain: clintsimon.com

encoding: UTF-8
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title
timezone: "US/Pacific"
exclude: [ "README.md", "*.sln", "*.suo", "~$*" ]

gravatar_url: "http://s.gravatar.com/avatar/6704ccdc544cd27a8445429aea61947e"
analytics_id: UA-25860409-1
webmaster_key: 9122UHrLTdTksyNCp_xG5dypMZu2evQmgwu43GVHjOo
twitter_username: "clintsim"
facebook_username: "csim74"
linkedin_username: "clintsimon"
github_username: "csim"
disqus_shortname: "csimme"
instagram_username: "csim74"

navigation:
    - { title: "About", url: "/about/" }
    - { title: "Archive", url: "/blog/archive/" }
    - { title: "Topics", url: "/blog/topics/" }
