name: csim
title: csim
author: Clint Simon
url: http://csim.me
domain: csim.me

markdown: redcarpet
permalink: /blog/:year/:month/:day/:title
timezone: "US/Pacific"
exclude: [ 'README.md', '*.sln', '*.suo' ]

analytics_id: UA-25860409-1
webmaster_key: 9122UHrLTdTksyNCp_xG5dypMZu2evQmgwu43GVHjOo

twitter_username: "clintsim"
facebook_username: "csim74"
linkedin_username: "clintsimon"
github_username: "csim"
disqus_shortname: "csimme"

navigation:
    - { title: "About", url: "/about/" }
    - { title: "Archive", url: "/blog/archive/" }
    - { title: "Topics", url: "/blog/topics/" }
