name: csim
title: Clint Simon
author: Clint Simon
url: http://csim.me

markdown: redcarpet
permalink: /:year/:month/:day/:title
timezone: "US/Pacific"
exclude: ['README.md']

twitter_username: "clintsim"
facebook_username: "csim74"
linkedin_username: "clintsimon"
github_username: "csim"
disqus_shortname: "csimme"
