baseurl = "http://clintsimon.com"
languageCode = "en-us"
title = "Clint Simon"
theme = "vienna"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "clintsim"
    github = "csim"
    linkedin = "clintsimon"
    googleplus = ""
    facebook = "csim74"
    stackoverflow = ""
    keybase = ""
    instagram = ""
    # Disqus shortname
    disqus = "clintsimon"
    # Google Analytics API key.
    ga_api_key = "UA-25860409-1"
    # Mixpanel API key.
    mixpanel_api_key = ""
    author = "Clint Simon"
    avatar = ""
    contact = ""
    bio = ""
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Find a way."
    themecolor = "" # Defines the tab color in Chrome for Android.